### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by EmilePerron** [roukmoute/hashids-bundle#18]
Hi there!

I see that there is PHP 8 support on the `v3` branch, but that it hasn't been released yet.
What is missing for this new release to be published?

I would like to use this package in my project, so I would be willing to help get V3 ready for release if that means I can use it sooner rather than later.

Cheers!

**Comment by roukmoute** [comment]
Hello !

Sorry for the delay of this answer.

I'm working on it right now.
I hope to provide you with a new version soon.

**Comment by roukmoute** [comment]
You can review https://github.com/roukmoute/hashids-bundle/pull/20 if you would like :)

**Comment by EmilePerron** [comment]
Thanks for the quick update! 

I've taken a look at the PR, and babaorum's comments seem to cover everything I had to mention. :)

**Comment by roukmoute** [comment]
https://github.com/roukmoute/hashids-bundle/releases/tag/v3.0.0
