### ISSUE TITLE
Autowiring conflicts with "passthrough" option ?

### ISSUE THREAD

**Issue by artyuum** [roukmoute/hashids-bundle#8]
Hi, great bundle it's working like a charm, except one thing.

I'm working with Symfony 4.3.1.

Here is my controller:
```php
/**
 * @Route("/{id}/download", name="download")
 * @param Wallpaper $wallpaper
 * @param DownloadHandler $downloadHandler
 * @return Response
 */
public function download(Wallpaper $wallpaper, DownloadHandler $downloadHandler)
{
    return $downloadHandler->downloadObject($wallpaper->getMedia(), 'uploadedFile');
}
```

And here is the error im getting:

> Argument 2 passed to App\Controller\WallpapersController::download() must be an instance of Vich\UploaderBundle\Handler\DownloadHandler, integer given, called in /mnt/c/Users/user/Documents/Dev/symfony/vendor/symfony/http-kernel/HttpKernel.php on line 151

I tried to pass another service to see if the error comes from the `DownloadHandler` but I have the same error, so it's not related to VichUploaderBundle.

When I disable the "passthrough" setting, Symfony is able to inject the proper service without this error.

Any idea ?

Thanks in advance.

**Comment by roukmoute** [comment]
Ok this is interesting. I will try it quickly.

**Comment by roukmoute** [comment]
Hi @artyuum,

sorry for the delay.

I've tried many things, but I don't have the same problem of yours.

Is it possible to try to give me a fonctionnal tests with your problem?

This is my default test:

```php
/**
 * @Route("/posts/{id}", methods={"GET"}, name="blog_post")
 */
public function postShow(Post $post): Response
{
    return $this->render('blog/post_show.html.twig', ['post' => $post]);
}
```

I've tried:

```php
/**
 * @Route("/posts/{id}", methods={"GET"}, name="blog_post")
 */
public function postShow(Post $post, AddUserCommand $addUserCommand): Response
{
    return $this->render('blog/post_show.html.twig', ['post' => $post]);
}
```

And:

```php
/**
 * @Route("/posts/{id}", methods={"GET"}, name="blog_post")
 */
public function postShow(Post $post, Request $request, PostRepository $posts, AddUserCommand $addUserCommand): Response
{
    return $this->render('blog/post_show.html.twig', ['post' => $post]);
}
```

**Comment by artyuum** [comment]
This is very odd, I don't have the issue anymore.
Sorry for wasting your time.

**Comment by artyuum** [comment]
I spoke too soon, when I pass a Symfony's component as argument I don't have any errors. Example: 
```php
/**
 * @Route("/{id}/download", name="download")
 * @param Wallpaper $wallpaper
 * @return Response
 */
public function download(Wallpaper $wallpaper, Request $request)
{
    return $this->file($mediaAPI->buildMediaPath($wallpaper));
}
```

But when I pass any other service, I have an error: 
```php
/**
 * @Route("/{id}/download", name="download")
 * @param Wallpaper $wallpaper
 * @return Response
 */
public function download(Wallpaper $wallpaper, MediaAPI $mediaAPI)
{
    return $this->file($mediaAPI->buildMediaPath($wallpaper));
}
```

> Argument 2 passed to App\Controller\WallpapersController::download() must be an instance of App\Service\MediaAPI, integer given


Can you please create a simple service and pass it as argument to see if I'm the only one having this issue or not?

Thanks in advance.

**Comment by roukmoute** [comment]
[my_project.zip](https://github.com/roukmoute/HashidsBundle/files/3359095/my_project.zip)
I've reused symfony demo.
Just do a `composer install`.
If you try this URL: `http(s:)//127.0.0.1:8000/fr/blog/posts/1` you should see the page.
But I've updated the controller to add my own stupid (Pouet) service.

So, if a day you have a time to create the bug, I take :-)

Thanks a lot for your help and sorry to do not found your problem.

**Comment by artyuum** [comment]
Thank you, I'll test your code this week-end and I'll come back to you.

**Comment by artyuum** [comment]
I actually had some time today and I was able to reproduce the issue on your demo project.
When you're passing the Post ID as integer, it works perfectly fine as it's the default behavior and it's not using your bundle in order to convert the Hashid to a Post ID.
So in order to get the encoded Post ID, I'm editing the `BlogController->postShow()` controller as follow:
```php
public function postShow(Post $post, Pouet $pouet, HashidsInterface $hashids): Response
{
    dump($hashids->encode($post->getId()));
    // Symfony's 'dump()' function is an improved version of PHP's 'var_dump()' but
    // it's not available in the 'prod' environment to prevent leaking sensitive information.
    // It can be used both in PHP files and Twig templates, but it requires to
    // have enabled the DebugBundle. Uncomment the following line to see it in action:
    //
    // dump($post, $this->getUser(), new \DateTime());

    return $this->render('blog/post_show.html.twig', ['post' => $post, 'pouet' => $pouet]);
}
```
And then, when I go on `/fr/blog/posts/1`, I can see the encoded Post ID, which is : **Jv**
Now when I go on `/fr/blog/posts/Jv`, I have the same issue:

> Argument 2 passed to App\Controller\BlogController::postShow() must be an instance of App\Pouet, integer given, called in /mnt/c/Users/user/Documents/Dev/my_project/vendor/symfony/http-kernel/HttpKernel.php on line 151

Can you reproduce the issue on your end?

**Comment by roukmoute** [comment]
Thanks a lot :-)

**Comment by artyuum** [comment]
Any idea on what caused the issue? Is this a bug in your package or in Symfony? Any ETA for the fix?

**Comment by roukmoute** [comment]
Hey,

I know how to fix it.  
You have pointed out a real problem, it is not possible to automate the road process, you will have to put a ParamConverter.  
But I have a few problem with my computer and I can't fix it for the moment.

**Comment by artyuum** [comment]
Sure, no problem.
Thanks for the workaround, it works.

**Comment by ArthurHoaro** [comment]
I'm not sure if that's what you meant, but I was able to work this around by making HashId's converter to fail on other dependency injection.

```php
/**
 * @Route("/template/{hashid}")
 * @ParamConverter("template", class="App\Entity\Template")
 * @ParamConverter("serializer", options={"hashid"="nope"})
 */
public function getTemplate(SerializerInterface $serializer, Template $template)
{
    $responseData = $serializer->serialize($template, 'json');
    return new Response($responseData, Response::HTTP_OK);
}
```

**Comment by artyuum** [comment]
@ArthurHoaro here is what worked for me: 
```php
    /**
     * @Route("/{id}/download", name="download")
     * @ParamConverter("id", class="\App\Entity\Wallpaper", options={"hashid" = "id"})
     * @param Wallpaper $wallpaper
     * @param MediaAPI $mediaAPI
     * @return Response
     */
    public function download(Wallpaper $wallpaper, MediaAPI $mediaAPI)
    {
        return $this->file($mediaAPI->buildPath($wallpaper));
    }
```

**Comment by artyuum** [comment]
Hi, the solution I found above doesn't work anymore...
Any update on this? Do you know what's causing the issue? I can help.

**Comment by roukmoute** [comment]
You can review https://github.com/roukmoute/hashids-bundle/pull/20 if you would like :)

**Comment by roukmoute** [comment]
https://github.com/roukmoute/hashids-bundle/releases/tag/v3.0.0
